<?php

namespace simserver\Resource;

class LanguageCode {

  use EnumLikeTrait;
  private static ?\ReflectionClass $reflector = null;

  /**
   * Get array of LanguageCode instances that match the given nation name.
   *
   * @param String $nationName  nation name to search for
   * @return Array              array of LanguageCode instances
   */
  public static function getByNationName(String $nationName): Array {

    $nationName = strtoupper(str_replace(" ", "_", trim($nationName)));
    $languageCodes = [];
    foreach (self::cases() as $case) {
      if (str_contains($case->name, $nationName)) {
        $languageCodes[] = $case;
      }
    }

    return $languageCodes;

  }

  public const LANG_AFRIKAANS                                = "af";
  public const LANG_AFRIKAANS_SOUTH_AFRICA                   = "af-ZA";
  public const LANG_ARABIC                                   = "ar";
  public const LANG_ARABIC_UAE                               = "ar-AE";
  public const LANG_ARABIC_BAHRAIN                           = "ar-BH";
  public const LANG_ARABIC_ALGERIA                           = "ar-DZ";
  public const LANG_ARABIC_EGYPT                             = "ar-EG";
  public const LANG_ARABIC_IRAQ                              = "ar-IQ";
  public const LANG_ARABIC_JORDAN                            = "ar-JO";
  public const LANG_ARABIC_KUWAIT                            = "ar-KW";
  public const LANG_ARABIC_LEBANON                           = "ar-LB";
  public const LANG_ARABIC_LIBYA                             = "ar-LY";
  public const LANG_ARABIC_MOROCCO                           = "ar-MA";
  public const LANG_ARABIC_OMAN                              = "ar-OM";
  public const LANG_ARABIC_QATAR                             = "ar-QA";
  public const LANG_ARABIC_SAUDI_ARABIA                      = "ar-SA";
  public const LANG_ARABIC_SYRIA                             = "ar-SY";
  public const LANG_ARABIC_TUNISIA                           = "ar-TN";
  public const LANG_ARABIC_YEMEN                             = "ar-YE";
  public const LANG_AZERI_LATIN                              = "az";
  public const LANG_AZERI_LATIN_AZERBAIJAN                   = "az-AZ";
  public const LANG_AZERI_CYRILLIC_AZERBAIJAN                = "az-AZ";
  public const LANG_BELARUSIAN                               = "be";
  public const LANG_BELARUSIAN_BELARUS                       = "be-BY";
  public const LANG_BULGARIAN                                = "bg";
  public const LANG_BULGARIAN_BULGARIA                       = "bg-BG";
  public const LANG_BOSNIAN_BOSNIA_AND_HERZEGOVINA           = "bs-BA";
  public const LANG_CATALAN                                  = "ca";
  public const LANG_CATALAN_SPAIN                            = "ca-ES";
  public const LANG_CZECH                                    = "cs";
  public const LANG_CZECH_CZECH_REPUBLIC                     = "cs-CZ";
  public const LANG_WELSH                                    = "cy";
  public const LANG_WELSH_UNITED_KINGDOM                     = "cy-GB";
  public const LANG_DANISH                                   = "da";
  public const LANG_DANISH_DENMARK                           = "da-DK";
  public const LANG_GERMAN                                   = "de";
  public const LANG_GERMAN_AUSTRIA                           = "de-AT";
  public const LANG_GERMAN_SWITZERLAND                       = "de-CH";
  public const LANG_GERMAN_GERMANY                           = "de-DE";
  public const LANG_GERMAN_LIECHTENSTEIN                     = "de-LI";
  public const LANG_GERMAN_LUXEMBOURG                        = "de-LU";
  public const LANG_DIVEHI                                   = "dv";
  public const LANG_DIVEHI_MALDIVES                          = "dv-MV";
  public const LANG_GREEK                                    = "el";
  public const LANG_GREEK_GREECE                             = "el-GR";
  public const LANG_ENGLISH                                  = "en";
  public const LANG_ENGLISH_AUSTRALIA                        = "en-AU";
  public const LANG_ENGLISH_BELIZE                           = "en-BZ";
  public const LANG_ENGLISH_CANADA                           = "en-CA";
  public const LANG_ENGLISH_CARIBBEAN                        = "en-CB";
  public const LANG_ENGLISH_UNITED_KINGDOM                   = "en-GB";
  public const LANG_ENGLISH_IRELAND                          = "en-IE";
  public const LANG_ENGLISH_JAMAICA                          = "en-JM";
  public const LANG_ENGLISH_NEW_ZEALAND                      = "en-NZ";
  public const LANG_ENGLISH_REPUBLIC_OF_THE_PHILIPPINES      = "en-PH";
  public const LANG_ENGLISH_TRINIDAD_AND_TOBAGO              = "en-TT";
  public const LANG_ENGLISH_UNITED_STATES                    = "en-US";
  public const LANG_ENGLISH_SOUTH_AFRICA                     = "en-ZA";
  public const LANG_ENGLISH_ZIMBABWE                         = "en-ZW";
  public const LANG_ESPERANTO                                = "eo";
  public const LANG_SPANISH                                  = "es";
  public const LANG_SPANISH_ARGENTINA                        = "es-AR";
  public const LANG_SPANISH_BOLIVIA                          = "es-BO";
  public const LANG_SPANISH_CHILE                            = "es-CL";
  public const LANG_SPANISH_COLOMBIA                         = "es-CO";
  public const LANG_SPANISH_COSTA_RICA                       = "es-CR";
  public const LANG_SPANISH_DOMINICAN_REPUBLIC               = "es-DO";
  public const LANG_SPANISH_ECUADOR                          = "es-EC";
  public const LANG_SPANISH_CASTILIAN                        = "es-ES";
  public const LANG_SPANISH_SPAIN                            = "es-ES";
  public const LANG_SPANISH_GUATEMALA                        = "es-GT";
  public const LANG_SPANISH_HONDURAS                         = "es-HN";
  public const LANG_SPANISH_MEXICO                           = "es-MX";
  public const LANG_SPANISH_NICARAGUA                        = "es-NI";
  public const LANG_SPANISH_PANAMA                           = "es-PA";
  public const LANG_SPANISH_PERU                             = "es-PE";
  public const LANG_SPANISH_PUERTO_RICO                      = "es-PR";
  public const LANG_SPANISH_PARAGUAY                         = "es-PY";
  public const LANG_SPANISH_EL_SALVADOR                      = "es-SV";
  public const LANG_SPANISH_URUGUAY                          = "es-UY";
  public const LANG_SPANISH_VENEZUELA                        = "es-VE";
  public const LANG_ESTONIAN                                 = "et";
  public const LANG_ESTONIAN_ESTONIA                         = "et-EE";
  public const LANG_BASQUE                                   = "eu";
  public const LANG_BASQUE_SPAIN                             = "eu-ES";
  public const LANG_FARSI                                    = "fa";
  public const LANG_FARSI_IRAN                               = "fa-IR";
  public const LANG_FINNISH                                  = "fi";
  public const LANG_FINNISH_FINLAND                          = "fi-FI";
  public const LANG_FAROESE                                  = "fo";
  public const LANG_FAROESE_FAROE_ISLANDS                    = "fo-FO";
  public const LANG_FRENCH                                   = "fr";
  public const LANG_FRENCH_BELGIUM                           = "fr-BE";
  public const LANG_FRENCH_CANADA                            = "fr-CA";
  public const LANG_FRENCH_SWITZERLAND                       = "fr-CH";
  public const LANG_FRENCH_FRANCE                            = "fr-FR";
  public const LANG_FRENCH_LUXEMBOURG                        = "fr-LU";
  public const LANG_FRENCH_PRINCIPALITY_OF_MONACO            = "fr-MC";
  public const LANG_GALICIAN                                 = "gl";
  public const LANG_GALICIAN_SPAIN                           = "gl-ES";
  public const LANG_GUJARATI                                 = "gu";
  public const LANG_GUJARATI_INDIA                           = "gu-IN";
  public const LANG_HEBREW                                   = "he";
  public const LANG_HEBREW_ISRAEL                            = "he-IL";
  public const LANG_HINDI                                    = "hi";
  public const LANG_HINDI_INDIA                              = "hi-IN";
  public const LANG_CROATIAN                                 = "hr";
  public const LANG_CROATIAN_BOSNIA_AND_HERZEGOVINA          = "hr-BA";
  public const LANG_CROATIAN_CROATIA                         = "hr-HR";
  public const LANG_HUNGARIAN                                = "hu";
  public const LANG_HUNGARIAN_HUNGARY                        = "hu-HU";
  public const LANG_ARMENIAN                                 = "hy";
  public const LANG_ARMENIAN_ARMENIA                         = "hy-AM";
  public const LANG_INDONESIAN                               = "id";
  public const LANG_INDONESIAN_INDONESIA                     = "id-ID";
  public const LANG_ICELANDIC                                = "is";
  public const LANG_ICELANDIC_ICELAND                        = "is-IS";
  public const LANG_ITALIAN                                  = "it";
  public const LANG_ITALIAN_SWITZERLAND                      = "it-CH";
  public const LANG_ITALIAN_ITALY                            = "it-IT";
  public const LANG_JAPANESE                                 = "ja";
  public const LANG_JAPANESE_JAPAN                           = "ja-JP";
  public const LANG_GEORGIAN                                 = "ka";
  public const LANG_GEORGIAN_GEORGIA                         = "ka-GE";
  public const LANG_KAZAKH                                   = "kk";
  public const LANG_KAZAKH_KAZAKHSTAN                        = "kk-KZ";
  public const LANG_KANNADA                                  = "kn";
  public const LANG_KANNADA_INDIA                            = "kn-IN";
  public const LANG_KOREAN                                   = "ko";
  public const LANG_KOREAN_KOREA                             = "ko-KR";
  public const LANG_KONKANI                                  = "kok";
  public const LANG_KONKANI_INDIA                            = "kok-IN";
  public const LANG_KYRGYZ                                   = "ky";
  public const LANG_KYRGYZ_KYRGYZSTAN                        = "ky-KG";
  public const LANG_LITHUANIAN                               = "lt";
  public const LANG_LITHUANIAN_LITHUANIA                     = "lt-LT";
  public const LANG_LATVIAN                                  = "lv";
  public const LANG_LATVIAN_LATVIA                           = "lv-LV";
  public const LANG_MAORI                                    = "mi";
  public const LANG_MAORI_NEW_ZEALAND                        = "mi-NZ";
  public const LANG_FYRO_MACEDONIAN                          = "mk";
  public const LANG_FYRO_YUGOSLAV_REPUBLIC_OF_MACEDONIA      = "mk-MK";
  public const LANG_MONGOLIAN                                = "mn";
  public const LANG_MONGOLIAN_MONGOLIA                       = "mn-MN";
  public const LANG_MARATHI                                  = "mr";
  public const LANG_MARATHI_INDIA                            = "mr-IN";
  public const LANG_MALAY                                    = "ms";
  public const LANG_MALAY_BRUNEI_DARUSSALAM                  = "ms-BN";
  public const LANG_MALAY_MALAYSIA                           = "ms-MY";
  public const LANG_MALTESE                                  = "mt";
  public const LANG_MALTESE_MALTA                            = "mt-MT";
  public const LANG_NORWEGIAN_BOKMÅL                         = "nb";
  public const LANG_NORWEGIAN_BOKMÅL_NORWAY                  = "nb-NO";
  public const LANG_DUTCH                                    = "nl";
  public const LANG_DUTCH_BELGIUM                            = "nl-BE";
  public const LANG_DUTCH_NETHERLANDS                        = "nl-NL";
  public const LANG_NORWEGIAN_NYNORSK_NORWAY                 = "nn-NO";
  public const LANG_NORTHERN_SOTHO                           = "ns";
  public const LANG_NORTHERN_SOTHO_SOUTH_AFRICA              = "ns-ZA";
  public const LANG_PUNJABI                                  = "pa";
  public const LANG_PUNJABI_INDIA                            = "pa-IN";
  public const LANG_POLISH                                   = "pl";
  public const LANG_POLISH_POLAND                            = "pl-PL";
  public const LANG_PASHTO                                   = "ps";
  public const LANG_PASHTO_AFGHANISTAN                       = "ps-AR";
  public const LANG_PORTUGUESE                               = "pt";
  public const LANG_PORTUGUESE_BRAZIL                        = "pt-BR";
  public const LANG_PORTUGUESE_PORTUGAL                      = "pt-PT";
  public const LANG_QUECHUA                                  = "qu";
  public const LANG_QUECHUA_BOLIVIA                          = "qu-BO";
  public const LANG_QUECHUA_ECUADOR                          = "qu-EC";
  public const LANG_QUECHUA_PERU                             = "qu-PE";
  public const LANG_ROMANIAN                                 = "ro";
  public const LANG_ROMANIAN_ROMANIA                         = "ro-RO";
  public const LANG_RUSSIAN                                  = "ru";
  public const LANG_RUSSIAN_RUSSIA                           = "ru-RU";
  public const LANG_SANSKRIT                                 = "sa";
  public const LANG_SANSKRIT_INDIA                           = "sa-IN";
  public const LANG_SAMI_NORTHERN                            = "se";
  public const LANG_SAMI_NORTHERN_FINLAND                    = "se-FI";
  public const LANG_SAMI_SKOLT_FINLAND                       = "se-FI";
  public const LANG_SAMI_INARI_FINLAND                       = "se-FI";
  public const LANG_SAMI_NORTHERN_NORWAY                     = "se-NO";
  public const LANG_SAMI_LULE_NORWAY                         = "se-NO";
  public const LANG_SAMI_SOUTHERN_NORWAY                     = "se-NO";
  public const LANG_SAMI_NORTHERN_SWEDEN                     = "se-SE";
  public const LANG_SAMI_LULE_SWEDEN                         = "se-SE";
  public const LANG_SAMI_SOUTHERN_SWEDEN                     = "se-SE";
  public const LANG_SLOVAK                                   = "sk";
  public const LANG_SLOVAK_SLOVAKIA                          = "sk-SK";
  public const LANG_SLOVENIAN                                = "sl";
  public const LANG_SLOVENIAN_SLOVENIA                       = "sl-SI";
  public const LANG_ALBANIAN                                 = "sq";
  public const LANG_ALBANIAN_ALBANIA                         = "sq-AL";
  public const LANG_SERBIAN_LATIN_BOSNIA_AND_HERZEGOVINA     = "sr-BA";
  public const LANG_SERBIAN_CYRILLIC_BOSNIA_AND_HERZEGOVINA  = "sr-BA";
  public const LANG_SERBIAN_LATIN_SERBIA_AND_MONTENEGRO      = "sr-SP";
  public const LANG_SERBIAN_CYRILLIC_SERBIA_AND_MONTENEGRO   = "sr-SP";
  public const LANG_SWEDISH                                  = "sv";
  public const LANG_SWEDISH_FINLAND                          = "sv-FI";
  public const LANG_SWEDISH_SWEDEN                           = "sv-SE";
  public const LANG_SWAHILI                                  = "sw";
  public const LANG_SWAHILI_KENYA                            = "sw-KE";
  public const LANG_SYRIAC                                   = "syr";
  public const LANG_SYRIAC_SYRIA                             = "syr-SY";
  public const LANG_TAMIL                                    = "ta";
  public const LANG_TAMIL_INDIA                              = "ta-IN";
  public const LANG_TELUGU                                   = "te";
  public const LANG_TELUGU_INDIA                             = "te-IN";
  public const LANG_THAI                                     = "th";
  public const LANG_THAI_THAILAND                            = "th-TH";
  public const LANG_TAGALOG                                  = "tl";
  public const LANG_TAGALOG_PHILIPPINES                      = "tl-PH";
  public const LANG_TSWANA                                   = "tn";
  public const LANG_TSWANA_SOUTH_AFRICA                      = "tn-ZA";
  public const LANG_TURKISH                                  = "tr";
  public const LANG_TURKISH_TURKEY                           = "tr-TR";
  public const LANG_TATAR                                    = "tt";
  public const LANG_TATAR_RUSSIA                             = "tt-RU";
  public const LANG_TSONGA                                   = "ts";
  public const LANG_UKRAINIAN                                = "uk";
  public const LANG_UKRAINIAN_UKRAINE                        = "uk-UA";
  public const LANG_URDU                                     = "ur";
  public const LANG_URDU_ISLAMIC_REPUBLIC_OF_PAKISTAN        = "ur-PK";
  public const LANG_UZBEK_LATIN                              = "uz";
  public const LANG_UZBEK_LATIN_UZBEKISTAN                   = "uz-UZ";
  public const LANG_UZBEK_CYRILLIC_UZBEKISTAN                = "uz-UZ";
  public const LANG_VIETNAMESE                               = "vi";
  public const LANG_VIETNAMESE_VIETNAM                       = "vi-VN";
  public const LANG_XHOSA                                    = "xh";
  public const LANG_XHOSA_SOUTH_AFRICA                       = "xh-ZA";
  public const LANG_CHINESE                                  = "zh";
  public const LANG_CHINESE_S                                = "zh-CN";
  public const LANG_CHINESE_HONGKONG                         = "zh-HK";
  public const LANG_CHINESE_MACAU                            = "zh-MO";
  public const LANG_CHINESE_SINGAPORE                        = "zh-SG";
  public const LANG_CHINESE_T                                = "zh-TW";
  public const LANG_ZULU                                     = "zu";
  public const LANG_ZULU_SOUTH_AFRICA                        = "zu-ZA";

}
